name: Publish Docker image

on:
  push:
    branches: main

jobs:
  push_to_registry:
    environment: dockerhub
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: taicareuser/taicare-docker-hub-repository

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./tapo-main/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: taicareuser/taicare-docker-hub-repository:latest